name: themes_sandbox
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  provider: ^6.0.3
  flutter_colorpicker: ^1.0.3
  flutter_lorem: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  editable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/customthemes.json

